language: elixir
elixir:
  - 1.6
  - 1.7
  - 1.8
  - 1.9
otp_release:
  - 19.3
  - 20.3
  - 21.0
  - 22.0
script:
  - mix test
  - echo $TRAVIS_ELIXIR_VERSION; dpkg --compare-versions $TRAVIS_ELIXIR_VERSION "gt" "1.7"; if [ $? -eq "0" ]; then MIX_ENV=test mix dialyzer --halt-exit-status; fi
cache:
  directories:
    - priv/plts
matrix:
  exclude:
    - elixir: 1.6
      otp_release: 21.0
    - elixir: 1.6
      otp_release: 22.0
    - elixir: 1.7
      otp_release: 19.3
    - elixir: 1.7
      otp_release: 20.3
    - elixir: 1.8
      otp_release: 19.3
    - elixir: 1.8
      otp_release: 20.3
    - elixir: 1.9
      otp_release: 19.3
    - elixir: 1.9
      otp_release: 20.3